---
version: 2

updates:

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "SAP/go-ase-team"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "SAP/go-ase-team"
