// Code generated by "stringer -type=BlobType"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_BLOB_FULLCLASSNAME-1]
}

const _BlobType_name = "TDS_BLOB_FULLCLASSNAME"

var _BlobType_index = [...]uint8{0, 22}

func (i BlobType) String() string {
	i -= 1
	if i >= BlobType(len(_BlobType_index)-1) {
		return "BlobType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BlobType_name[_BlobType_index[i]:_BlobType_index[i+1]]
}
