// Code generated by "stringer -type=BlobSerializationType"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NativeJavaSerialization-0]
	_ = x[NativeCharacterFormat-1]
	_ = x[BinaryData-2]
	_ = x[UnicharUTF16-3]
	_ = x[UnicharUTF8-4]
	_ = x[UnicharSCSU-5]
}

const _BlobSerializationType_name = "NativeJavaSerializationNativeCharacterFormatBinaryDataUnicharUTF16UnicharUTF8UnicharSCSU"

var _BlobSerializationType_index = [...]uint8{0, 23, 44, 54, 66, 77, 88}

func (i BlobSerializationType) String() string {
	if i >= BlobSerializationType(len(_BlobSerializationType_index)-1) {
		return "BlobSerializationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BlobSerializationType_name[_BlobSerializationType_index[i]:_BlobSerializationType_index[i+1]]
}
