// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_VOID-31]
	_ = x[TDS_IMAGE-34]
	_ = x[TDS_TEXT-35]
	_ = x[TDS_BLOB-36]
	_ = x[TDS_VARBINARY-37]
	_ = x[TDS_INTN-38]
	_ = x[TDS_VARCHAR-39]
	_ = x[TDS_BINARY-45]
	_ = x[TDS_CHAR-47]
	_ = x[TDS_INT1-48]
	_ = x[TDS_DATE-49]
	_ = x[TDS_BIT-50]
	_ = x[TDS_TIME-51]
	_ = x[TDS_INT2-52]
	_ = x[TDS_INT4-56]
	_ = x[TDS_SHORTDATE-58]
	_ = x[TDS_FLT4-59]
	_ = x[TDS_MONEY-60]
	_ = x[TDS_DATETIME-61]
	_ = x[TDS_FLT8-62]
	_ = x[TDS_UINT2-65]
	_ = x[TDS_UINT4-66]
	_ = x[TDS_UINT8-67]
	_ = x[TDS_UINTN-68]
	_ = x[TDS_SENSITIVITY-103]
	_ = x[TDS_BOUNDARY-104]
	_ = x[TDS_DECN-106]
	_ = x[TDS_NUMN-108]
	_ = x[TDS_FLTN-109]
	_ = x[TDS_MONEYN-110]
	_ = x[TDS_DATETIMN-111]
	_ = x[TDS_SHORTMONEY-122]
	_ = x[TDS_DATEN-123]
	_ = x[TDS_TIMEN-147]
	_ = x[TDS_XML-163]
	_ = x[TDS_UNITEXT-174]
	_ = x[TDS_LONGCHAR-175]
	_ = x[TDS_BIGDATETIMEN-187]
	_ = x[TDS_BIGTIMEN-188]
	_ = x[TDS_INT8-191]
	_ = x[TDS_LONGBINARY-225]
	_ = x[TDS_INTERVAL-46]
	_ = x[TDS_SINT1-176]
	_ = x[TDS_DATETIMEN-111]
	_ = x[TDS_USER_TEXT-19]
	_ = x[TDS_USER_IMAGE-20]
	_ = x[TDS_USER_UNITEXT-36]
}

const _DataType_name = "TDS_USER_TEXTTDS_USER_IMAGETDS_VOIDTDS_IMAGETDS_TEXTTDS_BLOBTDS_VARBINARYTDS_INTNTDS_VARCHARTDS_BINARYTDS_INTERVALTDS_CHARTDS_INT1TDS_DATETDS_BITTDS_TIMETDS_INT2TDS_INT4TDS_SHORTDATETDS_FLT4TDS_MONEYTDS_DATETIMETDS_FLT8TDS_UINT2TDS_UINT4TDS_UINT8TDS_UINTNTDS_SENSITIVITYTDS_BOUNDARYTDS_DECNTDS_NUMNTDS_FLTNTDS_MONEYNTDS_DATETIMNTDS_SHORTMONEYTDS_DATENTDS_TIMENTDS_XMLTDS_UNITEXTTDS_LONGCHARTDS_SINT1TDS_BIGDATETIMENTDS_BIGTIMENTDS_INT8TDS_LONGBINARY"

var _DataType_map = map[DataType]string{
	19:  _DataType_name[0:13],
	20:  _DataType_name[13:27],
	31:  _DataType_name[27:35],
	34:  _DataType_name[35:44],
	35:  _DataType_name[44:52],
	36:  _DataType_name[52:60],
	37:  _DataType_name[60:73],
	38:  _DataType_name[73:81],
	39:  _DataType_name[81:92],
	45:  _DataType_name[92:102],
	46:  _DataType_name[102:114],
	47:  _DataType_name[114:122],
	48:  _DataType_name[122:130],
	49:  _DataType_name[130:138],
	50:  _DataType_name[138:145],
	51:  _DataType_name[145:153],
	52:  _DataType_name[153:161],
	56:  _DataType_name[161:169],
	58:  _DataType_name[169:182],
	59:  _DataType_name[182:190],
	60:  _DataType_name[190:199],
	61:  _DataType_name[199:211],
	62:  _DataType_name[211:219],
	65:  _DataType_name[219:228],
	66:  _DataType_name[228:237],
	67:  _DataType_name[237:246],
	68:  _DataType_name[246:255],
	103: _DataType_name[255:270],
	104: _DataType_name[270:282],
	106: _DataType_name[282:290],
	108: _DataType_name[290:298],
	109: _DataType_name[298:306],
	110: _DataType_name[306:316],
	111: _DataType_name[316:328],
	122: _DataType_name[328:342],
	123: _DataType_name[342:351],
	147: _DataType_name[351:360],
	163: _DataType_name[360:367],
	174: _DataType_name[367:378],
	175: _DataType_name[378:390],
	176: _DataType_name[390:399],
	187: _DataType_name[399:415],
	188: _DataType_name[415:427],
	191: _DataType_name[427:435],
	225: _DataType_name[435:449],
}

func (i DataType) String() string {
	if str, ok := _DataType_map[i]; ok {
		return str
	}
	return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
}
