// SPDX-FileCopyrightText: 2020 SAP SE
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=DynamicOperationType"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_DYN_INVALID-0]
	_ = x[TDS_DYN_PREPARE-1]
	_ = x[TDS_DYN_EXEC-2]
	_ = x[TDS_DYN_DEALLOC-4]
	_ = x[TDS_DYN_EXEC_IMMED-8]
	_ = x[TDS_DYN_PROCNAME-16]
	_ = x[TDS_DYN_ACK-32]
	_ = x[TDS_DYN_DESCIN-64]
	_ = x[TDS_DYN_DESCOUT-128]
}

const (
	_DynamicOperationType_name_0 = "TDS_DYN_INVALIDTDS_DYN_PREPARETDS_DYN_EXEC"
	_DynamicOperationType_name_1 = "TDS_DYN_DEALLOC"
	_DynamicOperationType_name_2 = "TDS_DYN_EXEC_IMMED"
	_DynamicOperationType_name_3 = "TDS_DYN_PROCNAME"
	_DynamicOperationType_name_4 = "TDS_DYN_ACK"
	_DynamicOperationType_name_5 = "TDS_DYN_DESCIN"
	_DynamicOperationType_name_6 = "TDS_DYN_DESCOUT"
)

var (
	_DynamicOperationType_index_0 = [...]uint8{0, 15, 30, 42}
)

func (i DynamicOperationType) String() string {
	switch {
	case i <= 2:
		return _DynamicOperationType_name_0[_DynamicOperationType_index_0[i]:_DynamicOperationType_index_0[i+1]]
	case i == 4:
		return _DynamicOperationType_name_1
	case i == 8:
		return _DynamicOperationType_name_2
	case i == 16:
		return _DynamicOperationType_name_3
	case i == 32:
		return _DynamicOperationType_name_4
	case i == 64:
		return _DynamicOperationType_name_5
	case i == 128:
		return _DynamicOperationType_name_6
	default:
		return "DynamicOperationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
