// SPDX-FileCopyrightText: 2020 SAP SE
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=EEDStatus"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_NO_EED-0]
	_ = x[TDS_EED_FOLLOWS-1]
	_ = x[TDS_EED_INFO-2]
}

const _EEDStatus_name = "TDS_NO_EEDTDS_EED_FOLLOWSTDS_EED_INFO"

var _EEDStatus_index = [...]uint8{0, 10, 25, 37}

func (i EEDStatus) String() string {
	if i >= EEDStatus(len(_EEDStatus_index)-1) {
		return "EEDStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EEDStatus_name[_EEDStatus_index[i]:_EEDStatus_index[i+1]]
}
