// Code generated by "stringer -type=LanguageStatus"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_LANGUAGE_NOARGS-0]
}

const _LanguageStatus_name = "TDS_LANGUAGE_NOARGS"

var _LanguageStatus_index = [...]uint8{0, 19}

func (i LanguageStatus) String() string {
	if i < 0 || i >= LanguageStatus(len(_LanguageStatus_index)-1) {
		return "LanguageStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LanguageStatus_name[_LanguageStatus_index[i]:_LanguageStatus_index[i+1]]
}
