// Code generated by "stringer -type=LoginSec"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_SEC_LOG_ENCRYPT-1]
}

const _LoginSec_name = "TDS_SEC_LOG_ENCRYPT"

var _LoginSec_index = [...]uint8{0, 19}

func (i LoginSec) String() string {
	i -= 1
	if i >= LoginSec(len(_LoginSec_index)-1) {
		return "LoginSec(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LoginSec_name[_LoginSec_index[i]:_LoginSec_index[i+1]]
}
