// Code generated by "stringer -type=LoginAckStatus"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_LOG_SUCCEED-5]
	_ = x[TDS_LOG_FAIL-6]
	_ = x[TDS_LOG_NEGOTIATE-7]
}

const _LoginAckStatus_name = "TDS_LOG_SUCCEEDTDS_LOG_FAILTDS_LOG_NEGOTIATE"

var _LoginAckStatus_index = [...]uint8{0, 15, 27, 44}

func (i LoginAckStatus) String() string {
	i -= 5
	if i >= LoginAckStatus(len(_LoginAckStatus_index)-1) {
		return "LoginAckStatus(" + strconv.FormatInt(int64(i+5), 10) + ")"
	}
	return _LoginAckStatus_name[_LoginAckStatus_index[i]:_LoginAckStatus_index[i+1]]
}
