// Code generated by "stringer -type=MessageHeaderStatus"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_BUFSTAT_EOM-1]
}

const _MessageHeaderStatus_name = "TDS_BUFSTAT_EOM"

var _MessageHeaderStatus_index = [...]uint8{0, 15}

func (i MessageHeaderStatus) String() string {
	i -= 1
	if i >= MessageHeaderStatus(len(_MessageHeaderStatus_index)-1) {
		return "MessageHeaderStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageHeaderStatus_name[_MessageHeaderStatus_index[i]:_MessageHeaderStatus_index[i+1]]
}
