// Code generated by "stringer -type=MessageHeaderStatus"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_BUFSTAT_EOM-1]
	_ = x[TDS_BUFSTAT_ATTNACK-2]
	_ = x[TDS_BUFSTAT_ATTN-4]
	_ = x[TDS_BUFSTAT_EVENT-8]
	_ = x[TDS_BUFSTAT_SEAL-16]
	_ = x[TDS_BUFSTAT_ENCRYPT-32]
	_ = x[TDS_BUFSTAT_SYMENCRYPT-64]
}

const (
	_MessageHeaderStatus_name_0 = "TDS_BUFSTAT_EOMTDS_BUFSTAT_ATTNACK"
	_MessageHeaderStatus_name_1 = "TDS_BUFSTAT_ATTN"
	_MessageHeaderStatus_name_2 = "TDS_BUFSTAT_EVENT"
	_MessageHeaderStatus_name_3 = "TDS_BUFSTAT_SEAL"
	_MessageHeaderStatus_name_4 = "TDS_BUFSTAT_ENCRYPT"
	_MessageHeaderStatus_name_5 = "TDS_BUFSTAT_SYMENCRYPT"
)

var (
	_MessageHeaderStatus_index_0 = [...]uint8{0, 15, 34}
)

func (i MessageHeaderStatus) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _MessageHeaderStatus_name_0[_MessageHeaderStatus_index_0[i]:_MessageHeaderStatus_index_0[i+1]]
	case i == 4:
		return _MessageHeaderStatus_name_1
	case i == 8:
		return _MessageHeaderStatus_name_2
	case i == 16:
		return _MessageHeaderStatus_name_3
	case i == 32:
		return _MessageHeaderStatus_name_4
	case i == 64:
		return _MessageHeaderStatus_name_5
	default:
		return "MessageHeaderStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
