// SPDX-FileCopyrightText: 2020 SAP SE
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=odceCipher"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[aes_256_cbc-0]
}

const _odceCipher_name = "aes_256_cbc"

var _odceCipher_index = [...]uint8{0, 11}

func (i odceCipher) String() string {
	if i < 0 || i >= odceCipher(len(_odceCipher_index)-1) {
		return "odceCipher(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _odceCipher_name[_odceCipher_index[i]:_odceCipher_index[i+1]]
}
