// SPDX-FileCopyrightText: 2020 SAP SE
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=OptionCmd"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_OPT_SET-1]
	_ = x[TDS_OPT_DEFAULT-2]
	_ = x[TDS_OPT_LIST-3]
	_ = x[TDS_OPT_INFO-4]
}

const _OptionCmd_name = "TDS_OPT_SETTDS_OPT_DEFAULTTDS_OPT_LISTTDS_OPT_INFO"

var _OptionCmd_index = [...]uint8{0, 11, 26, 38, 50}

func (i OptionCmd) String() string {
	i -= 1
	if i >= OptionCmd(len(_OptionCmd_index)-1) {
		return "OptionCmd(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _OptionCmd_name[_OptionCmd_index[i]:_OptionCmd_index[i+1]]
}
