// SPDX-FileCopyrightText: 2020 SAP SE
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=RowFmtStatus"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_ROW_NOSTATUS-0]
	_ = x[TDS_ROW_HIDDEN-1]
	_ = x[TDS_ROW_KEY-2]
	_ = x[TDS_ROW_VERSION-4]
	_ = x[TDS_ROW_COLUMNSTATUS-8]
	_ = x[TDS_ROW_UPDATEABLE-16]
	_ = x[TDS_ROW_NULLALLOWED-32]
	_ = x[TDS_ROW_IDENTITY-64]
	_ = x[TDS_ROW_PADCHAR-128]
}

const (
	_RowFmtStatus_name_0 = "TDS_ROW_NOSTATUSTDS_ROW_HIDDENTDS_ROW_KEY"
	_RowFmtStatus_name_1 = "TDS_ROW_VERSION"
	_RowFmtStatus_name_2 = "TDS_ROW_COLUMNSTATUS"
	_RowFmtStatus_name_3 = "TDS_ROW_UPDATEABLE"
	_RowFmtStatus_name_4 = "TDS_ROW_NULLALLOWED"
	_RowFmtStatus_name_5 = "TDS_ROW_IDENTITY"
	_RowFmtStatus_name_6 = "TDS_ROW_PADCHAR"
)

var (
	_RowFmtStatus_index_0 = [...]uint8{0, 16, 30, 41}
)

func (i RowFmtStatus) String() string {
	switch {
	case i <= 2:
		return _RowFmtStatus_name_0[_RowFmtStatus_index_0[i]:_RowFmtStatus_index_0[i+1]]
	case i == 4:
		return _RowFmtStatus_name_1
	case i == 8:
		return _RowFmtStatus_name_2
	case i == 16:
		return _RowFmtStatus_name_3
	case i == 32:
		return _RowFmtStatus_name_4
	case i == 64:
		return _RowFmtStatus_name_5
	case i == 128:
		return _RowFmtStatus_name_6
	default:
		return "RowFmtStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
