// Code generated by "stringer -type=TDSSecurity"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_MSG_SEC_ENCRYPT-0]
	_ = x[TDS_MSG_SEC_LOGPWD-1]
	_ = x[TDS_MSG_SEC_REMPWD-2]
	_ = x[TDS_MSG_SEC_CHALLENGE-3]
	_ = x[TDS_MSG_SEC_RESPONSE-4]
	_ = x[TDS_MSG_SEC_GETLABEL-5]
	_ = x[TDS_MSG_SEC_LABEL-6]
	_ = x[TDS_MSG_SQL_TBLNAME-7]
	_ = x[TDS_MSG_GW_RESERVED-8]
	_ = x[TDS_MSG_OMNI_CAPABILITIES-9]
	_ = x[TDS_MSG_SEC_OPAQUE-10]
	_ = x[TDS_MSG_HAFAILOVER-11]
	_ = x[TDS_MSG_EMPTY-12]
	_ = x[TDS_MSG_SEC_ENCRYPT2-13]
	_ = x[TDS_MSG_SEC_LOGPWD2-14]
	_ = x[TDS_MSG_SEC_SUP_CIPHER2-15]
	_ = x[TDS_MSG_MIG_REQ-16]
	_ = x[TDS_MSG_MIG_SYNC-17]
	_ = x[TDS_MSG_MIG_CONT-18]
	_ = x[TDS_MSG_MIG_IGN-19]
	_ = x[TDS_MSG_MIG_FAIL-20]
	_ = x[TDS_MSG_SEC_REMPWD2-21]
	_ = x[TDS_MSG_MIG_RESUME-22]
}

const _TDSSecurity_name = "TDS_MSG_SEC_ENCRYPTTDS_MSG_SEC_LOGPWDTDS_MSG_SEC_REMPWDTDS_MSG_SEC_CHALLENGETDS_MSG_SEC_RESPONSETDS_MSG_SEC_GETLABELTDS_MSG_SEC_LABELTDS_MSG_SQL_TBLNAMETDS_MSG_GW_RESERVEDTDS_MSG_OMNI_CAPABILITIESTDS_MSG_SEC_OPAQUETDS_MSG_HAFAILOVERTDS_MSG_EMPTYTDS_MSG_SEC_ENCRYPT2TDS_MSG_SEC_LOGPWD2TDS_MSG_SEC_SUP_CIPHER2TDS_MSG_MIG_REQTDS_MSG_MIG_SYNCTDS_MSG_MIG_CONTTDS_MSG_MIG_IGNTDS_MSG_MIG_FAILTDS_MSG_SEC_REMPWD2TDS_MSG_MIG_RESUME"

var _TDSSecurity_index = [...]uint16{0, 19, 37, 55, 76, 96, 116, 133, 152, 171, 196, 214, 232, 245, 265, 284, 307, 322, 338, 354, 369, 385, 404, 422}

func (i TDSSecurity) String() string {
	if i >= TDSSecurity(len(_TDSSecurity_index)-1) {
		return "TDSSecurity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TDSSecurity_name[_TDSSecurity_index[i]:_TDSSecurity_index[i+1]]
}
