// Code generated by "stringer -type=TDSToken"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_CURDECLARE3-16]
}

const _TDSToken_name = "TDS_CURDECLARE3"

var _TDSToken_index = [...]uint8{0, 15}

func (i TDSToken) String() string {
	i -= 16
	if i >= TDSToken(len(_TDSToken_index)-1) {
		return "TDSToken(" + strconv.FormatInt(int64(i+16), 10) + ")"
	}
	return _TDSToken_name[_TDSToken_index[i]:_TDSToken_index[i+1]]
}
