// Code generated by "stringer -type=TransState"; DO NOT EDIT.

package tds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TDS_TRAN_UNDEFINED-0]
}

const _TransState_name = "TDS_TRAN_UNDEFINED"

var _TransState_index = [...]uint8{0, 18}

func (i TransState) String() string {
	if i >= TransState(len(_TransState_index)-1) {
		return "TransState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransState_name[_TransState_index[i]:_TransState_index[i+1]]
}
